apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: flaskdeploy
  name: flaskdeploy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
    nodePort: 30111
  selector:
    app: flaskdeploy
  type: NodePort
status:
  loadBalancer: {}
